version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "3000:80"
    container_name: sn_nginx
  sn-api:
    image: node:18-buster-slim
    volumes:
      - ./:/var/www
  db:
    image: mysql
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_development_SocialNetwork
    ports:
      - "3000:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: sn-db
