name: Create docker image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Build image
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u "aretemal" --password-stdin
          docker image build -t aretemal/sn-api:latest .
          docker push aretemal/sn-api:latest
